create table attendance (date date not null, employee_id bigint not null, id bigint not null auto_increment, status varchar(255) not null, primary key (id)) engine=InnoDB;
create table audit_log (id bigint not null auto_increment, timestamp datetime(6), user_id bigint, action varchar(255), entity varchar(255), primary key (id)) engine=InnoDB;
create table department (id bigint not null auto_increment, description varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table employee (is_deleted BIT(1) DEFAULT 0 not null, salary float(53) not null, created_at datetime(6), department_id bigint not null, id bigint not null auto_increment, profile_image_id bigint, version bigint, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table employee_project (assigned_date date, employee_id bigint not null, project_id bigint not null, role varchar(255), primary key (employee_id, project_id)) engine=InnoDB;
create table project (id bigint not null auto_increment, description varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table refresh_token (expiry_date datetime(6), id bigint not null auto_increment, token varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table salary_history (effective_from date not null, effective_to date, salary float(53) not null, employee_id bigint not null, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table user_profiles (id bigint not null auto_increment, user_id bigint, file_name varchar(255), file_path varchar(255), file_type varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, created_at datetime(6), employee_id bigint, id bigint not null auto_increment, profile_image_id bigint, email varchar(255), name varchar(255), password varchar(255), phone_number varchar(255), role enum ('EMPLOYEE_VIEWER','SYSTEM_ADMIN','USER','USER_ADMIN'), primary key (id)) engine=InnoDB;
alter table department add constraint UK1t68827l97cwyxo9r1u6t4p7d unique (name);
alter table employee add constraint UKfopic1oh5oln2khj8eat6ino0 unique (email);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UK9q63snka3mdh91as4io72espi unique (phone_number);
alter table attendance add constraint FKr7q0h8jfngkyybll6o9r3h9ua foreign key (employee_id) references employee (id);
alter table employee add constraint FKbejtwvg9bxus2mffsm3swj3u9 foreign key (department_id) references department (id);
alter table employee_project add constraint FKb25s5hgggo6k4au4sye7teb3a foreign key (employee_id) references employee (id);
alter table employee_project add constraint FK4yddvnm7283a40plkcti66wv9 foreign key (project_id) references project (id);
alter table salary_history add constraint FKh8i8scfs62f1ke7xb28xcrsk1 foreign key (employee_id) references employee (id);
alter table user_profiles add constraint FKjcad5nfve11khsnpwj1mv8frj foreign key (user_id) references users (id);
